server:
  port: 8002                                                # 端口号

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zhujuming.vip.common.model      # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件
spring:
  application:
    name: system-service-provider                           # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://106.13.11.217:3306/cloudDB02          # 数据库名称
    username: root                                          # Mysql用户名
    password: 123456                                        # Mysql密码
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

logging:
  config: classpath:logback-dev.xml                         # 日志读取logback-dev.xml 文件

eureka:
  client:                                                   # 客户端注册进Eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: service-provider:8002                      # 主机名称:服务名称修改
    prefer-ip-address: true                                 # 访问路径可以显示IP地址

info:
  app.name: seven-system-parent
  company.name: www.zhujuming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
