server:
  port: 9527                                                # 端口号

spring:
  application:
    name: seven-system-zuul

logging:
  config: classpath:logback-dev.xml                         # 日志读取logback-dev.xml 文件

eureka:
  client:                                                   # 客户端注册进Eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: service-zuul:9527                          # 主机名称:服务名称修改
    prefer-ip-address: true                                 # 访问路径可以显示IP地址

zuul:
  routes:
    mydept.serviceId: system-service-provider
    mydept.path: /mydept/**

info:
  app.name: seven-system-parent
  company.name: www.zhujuming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
