server:
  port: 80                                  # 端口号

logging:
  config: classpath:logback-dev.xml         # 日志读取logback-dev.xml 文件  # false表示不向注册中心注册自己

eureka:
  client:
    register-with-eureka: false             # false表示不向注册中心注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/